defmodule TWSAPIEx.ServerVersions do
  @moduledoc """
  The known server versions.
  """

  import SimpleEnum, only: [defenum: 3]

  defenum(:min_server_ver, [allow_duplicate: true],
    # real_time_bars: 34,
    # scale_orders: 35,
    # snapshot_mkt_data: 35,
    # sshort_combo_legs: 35,
    # what_if_orders: 36,
    # contract_conid: 37,
    pta_orders: 39,
    fundamental_data: 40,
    delta_neutral: 40,
    contract_data_chain: 40,
    scale_orders2: 40,
    algo_orders: 41,
    execution_data_chain: 42,
    not_held: 44,
    sec_id_type: 45,
    place_order_conid: 46,
    req_mkt_data_conid: 47,
    req_calc_implied_volat: 49,
    req_calc_option_price: 50,
    sshortx_old: 51,
    sshortx: 52,
    req_global_cancel: 53,
    hedge_orders: 54,
    req_market_data_type: 55,
    opt_out_smart_routing: 56,
    smart_combo_routing_params: 57,
    delta_neutral_conid: 58,
    scale_orders3: 60,
    order_combo_legs_price: 61,
    trailing_percent: 62,
    delta_neutral_open_close: 66,
    positions: 67,
    account_summary: 67,
    trading_class: 68,
    scale_table: 69,
    linking: 70,
    algo_id: 71,
    optional_capabilities: 72,
    order_solicited: 73,
    linking_auth: 74,
    primaryexch: 75,
    randomize_size_and_price: 76,
    fractional_positions: 101,
    pegged_to_benchmark: 102,
    models_support: 103,
    sec_def_opt_params_req: 104,
    ext_operator: 105,
    soft_dollar_tier: 106,
    req_family_codes: 107,
    req_matching_symbols: 108,
    past_limit: 109,
    md_size_multiplier: 110,
    cash_qty: 111,
    req_mkt_depth_exchanges: 112,
    tick_news: 113,
    req_smart_components: 114,
    req_news_providers: 115,
    req_news_article: 116,
    req_historical_news: 117,
    req_head_timestamp: 118,
    req_histogram: 119,
    service_data_type: 120,
    agg_group: 121,
    underlying_info: 122,
    cancel_headtimestamp: 123,
    synt_realtime_bars: 124,
    cfd_reroute: 125,
    market_rules: 126,
    pnl: 127,
    news_query_origins: 128,
    unrealized_pnl: 129,
    historical_ticks: 130,
    market_cap_price: 131,
    pre_open_bid_ask: 132,
    real_expiration_date: 134,
    realized_pnl: 135,
    last_liquidity: 136,
    tick_by_tick: 137,
    decision_maker: 138,
    mifid_execution: 139,
    tick_by_tick_ignore_size: 140,
    auto_price_for_hedge: 141,
    what_if_ext_fields: 142,
    scanner_generic_opts: 143,
    api_bind_order: 144,
    order_container: 145,
    smart_depth: 146,
    remove_null_all_casting: 147,
    d_peg_orders: 148,
    mkt_depth_prim_exchange: 149,
    completed_orders: 150,
    price_mgmt_algo: 151,
    stock_type: 152,
    encode_msg_ascii7: 153,
    send_all_family_codes: 154,
    no_default_open_close: 155,
    price_based_volatility: 156,
    replace_fa_end: 157
  )

  # 100+ messaging */
  # 100 = enhanced handshake, msg length prefixes

  def min_client_ver(), do: 100
  def max_client_ver(), do: 157
end
